# Generated by Django 5.0.6 on 2024-06-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIHit',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_type', models.CharField(max_length=10)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('payload', models.TextField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_address', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=50)),
                ('user_agent', models.CharField(max_length=100)),
            ],
        ),
    ]
