# Generated by Django 5.0.6 on 2024-06-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tracker_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apihit',
            name='request_path',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
