# Generated by Django 5.0.6 on 2024-06-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tracker_api', '0002_apihit_request_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apihit',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apihit',
            name='os',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='apihit',
            name='user_agent',
            field=models.CharField(max_length=255),
        ),
    ]
